name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Add your PHP-related steps here (e.g., linting, testing)
    - name: Run PHP Lint
      run: find . -name "*.php" -print0 | xargs -0 -n1 php -l
